name: CI & Deploy

permissions:
  contents: read
  packages: write
  
on:
  push:
    branches: [main]

jobs:
  build-test-deploy:
    runs-on: self-hosted

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: kubsu
          POSTGRES_USER: kubsu
          POSTGRES_PASSWORD: kubsu
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U kubsu"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Wait for Postgres
        run: |
          echo "Sleeping 20s for Postgres to initialize..."
          sleep 20

      - name: Initialize DB from dump
        run: |
          cat "${{ github.workspace }}/kubsu/dump.sql" \
            | docker run --rm -i \
                --network host \
                -e PGPASSWORD=kubsu \
                postgres:14 \
                psql -h localhost -U kubsu -d kubsu

      - name: Build test image (builder stage)
        run: |
          docker build \
            --target builder \
            --file docker/Dockerfile \
            --tag myapp:test \
            docker/

      - name: Run tests
        run: |
          docker run --rm \
            --network host \
            -e DB_HOST=localhost \
            -e DB_PORT=5432 \
            -e DB_USER=kubsu \
            -e DB_PASS=kubsu \
            -e DB_NAME=kubsu \
            -e PYTHONPATH=/app \
            myapp:test \
            pytest tests

      - name: Build prod image
        run: |
          docker build \
            --file docker/Dockerfile \
            --tag myapp:latest \
            docker/

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag and push to GHCR
        run: |
          GHCR_IMAGE=ghcr.io/${{ github.repository_owner }}/myapp:latest
          docker tag myapp:latest $GHCR_IMAGE
          docker push $GHCR_IMAGE

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to remote server
        env:
          GHCR_IMAGE: ghcr.io/${{ github.repository_owner }}/myapp:latest
          SSH_USER:   ${{ secrets.SSH_USER }}
          SSH_HOST:   ${{ secrets.SSH_HOST }}
          SSH_PORT:   ${{ secrets.SSH_PORT }}
          APP_PORT:   8010
        run: |
          ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USER@$SSH_HOST <<EOF
            echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u ${{ github.actor }} --password-stdin
            podman pull $GHCR_IMAGE
            podman run -d \
              --name myapp \
              --network host \
              -e PORT=$APP_PORT \
              $GHCR_IMAGE \
              uvicorn src.main:app --host 0.0.0.0 --port $APP_PORT
          EOF
