name: CI & Deploy

on:
  push:
    branches: [main]

jobs:
  build-test-deploy:
    runs-on: self-hosted
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: kubsu
          POSTGRES_USER: kubsu
          POSTGRES_PASSWORD: kubsu
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U kubsu"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Wait for Postgres and initialize DB
        run: |
          timeout=5
          start_time=$SECONDS
          while ! pg_isready -h localhost -p 5432 -U kubsu; do
            if [ $((SECONDS - start_time)) -ge $timeout ]; then
              echo "Postgres не стал доступен в течение $timeout секунд. Пропускаем инициализацию БД."
              break
            fi
            echo "Ожидаем Postgres..."
            sleep 1
          done
          if pg_isready -h localhost -p 5432 -U kubsu; then
            psql postgresql://kubsu:kubsu@localhost:5432/kubsu -f kubsu/dump.sql
          else
            echo "Пропускаем инициализацию БД из-за превышения времени ожидания подключения."
          fi

      - name: Build test image
        run: docker build --target builder -t myapp:test .

      - name: Run tests
        run: |
          docker run --rm \
            --network host \
            -e PYTHONPATH=/app \
            myapp:test \
            pytest tests

      - name: Build prod image
        run: docker build -t myapp:latest .

      - name: Set up SSH
        run: |
              echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/ssh_key
              chmod 600 /tmp/ssh_key
              ssh-agent -a /tmp/ssh_agent.sock
              SSH_AUTH_SOCK=/tmp/ssh_agent.sock ssh-add /tmp/ssh_key

      - name: Deploy to remote server
        run: |
          docker save myapp:latest | \
            ssh -o StrictHostKeyChecking=no \
                -p ${{ secrets.SSH_PORT }} \
                ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
            "podman load && \
             podman tag myapp:latest myapp:latest && \
             podman run -d \
               --name myapp \
               --network host \
               myapp:latest \
               uvicorn src.main:app --host 0.0.0.0 --port 8010"
